docs: improve documents
siyul-park/uniflow pull request #176
Opened 2024-08-09 10:25 UTC by siyul-park

### **Changes Made**

### **Related Issues**

### **Additional Information**

2024-08-18 00:38 UTC, siyul-park commented on docs/user_extensions_kr.md
> +## 명세서 작성
명세서란 단어보다는 핵심 개념에 적혀 있는 워크플로우란 명칭을 사용하는것이 적절할거 같아요.

또한 새로운 노드 종류를 추가하는 부분이랑 워크플로우를 작성하는 부분은 작성 주체가 다를 수 있는 별개의 과정이므로 그 부분이 명확하게 들어나면 더 좋겠어요.

2024-08-18 00:38 UTC, siyul-park commented on docs/architecture_kr.md
> +```text
모든 문서들이 동일한 타입을 사용하도록 통일을 하면 좋겠어요.

2024-08-18 00:38 UTC, siyul-park commented on docs/architecture_kr.md
> +      code: "null"
코드내에 js와 같은 언어가 들어갈 수 있어 " 보다 ' 가 더 내부 값을 이스케이프 하는 경우가 적어 보기 더 편할것 같아요

2024-08-18 00:38 UTC, siyul-park commented on docs/user_extensions_kr.md
> +만약 추가로 받을 값이 필요하다면, 필수 항목을 제외하고 추가적인 항목을 작성하면 됩니다. 이후 명세서에서 노드를 사용할 때 추가 필드로 사용할 수 있게 되며, 환경 변수 등 명세서에 선언할 때 초기 설정 값으로 받아들일 수 있습니다. 예시로 다양한 언어를 지원하기 위해 코드가 있는 code 필드와 어떤 코드인지에 대한 정보인 language 필드를 받고
명세서에서 노드를 사용할때 -> 워크플로우에 노드 명세를 정의할때

2024-08-18 00:38 UTC, siyul-park commented on docs/user_extensions_kr.md
> +  name: pong
실제로 만든 my-snippet과 노드 명세의 스미카가 다른거 같아요

2024-08-18 00:38 UTC, siyul-park commented on docs/user_extensions_kr.md
> +이후 이 두개의 값은 명세서에서 추가 필드로 인식되며, 넣은 값을 직접적으로 사용하거나 다른 노드에게 처리 과정을 지시할 수 있게 됩니다.
명세서 -> 노드 명세

2024-08-18 00:38 UTC, siyul-park commented on docs/user_extensions_kr.md
> +  if outPayload, err := types.Encoder.Encode(input); err == nil {
인풋을 디코딩했다가 다시 인코딩 하는 과정은 불필요한거 같아요.

그리고 노드의 동작이 snippet 보다는 loopback 에 더 맞는거 같아요. 노드의 이름을 바꾸는것은 어떤가요?

2024-08-18 00:38 UTC, siyul-park commented on docs/user_extensions_kr.md
> +	Language  string `map:"language,omitempty"` // <- 언어 종류
노드에서 사용되지 않아 불필요한 필드인거 같아요

2024-09-16 16:56 UTC, ewlkkf requested changes
다시 한번 가이드 변경해서 조정했는데, 그동안 main에서 커밋된 사항들을 끌어오면서 뭔가 잔뜩 커밋이 발생해버렸으니 추가 확인 필요함.

2024-09-17 00:36 UTC, merged